export const initialSettings = {
  image: {
    url: null,
    blob: null,
  },
  imageBlob: null,
  fullName: null,
  phoneNumber: null,
  email: null,
  address: null,
  intro: null,
  skills: [],
  languages: [],
  experience: [],
  education: [],
  desiredPositions: [],
  expectedSalary: null,
  websiteDesign: null,
  subdomainStatus: null,
  subdomainCode: null,
  userStatus: null,
};
